name: 'Get CSProj Version'
description: 'Retrieves the current version from a given .csproj'
branding:
  icon: anchor
  color: blue
inputs:
  file:
    description: |
      'The .csproj from which to read the version.'
      'Set if you need to read a different file / or different folder.'
    required: true
  regex:
    description: |
      'ECMAScript Regular Expression to parse the version string for verification.'
      'Defaults to being semver, i.e. "major.minor.patch"'
      'Set if you to be compatible with a different, non-semver format.'
    required: false
    default: '^(?<major>[0-9]+)\.(?<minor>[0-9]+)\.(?<patch>[0-9]+)$'
  xpath:
    description: |
      'XPath to version element.'
    required: false
    default: '//PropertyGroup/Version'
outputs:
  version:
    description: 'Retrieved and verified version string'
runs:
  using: 'node12'
  main: 'dist/index.js'
