on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test functionality
        uses: ./ # Uses an action in the root directory
        id: test
        with:
          version: '1.2.3'

      - name: Print results
        run: echo ${{ steps.test.outputs.version }}

      - name: Verify results
        if: ${{ steps.test.outputs.version == '1.2.3' }}
        run: echo "Setting the version worked"
      - name: Verify results (negative case)
        if: ${{ steps.test.outputs.version != '1.2.3' }}
        run: |
          echo "Setting the version did not work"
          exit -1

      - name: Test functionality with params
        uses: ./ # Uses an action in the root directory
        id: testparams
        with:
          file: 'package.json'
          regex: '^(?<major>[0-9]+)\.(?<minor>[0-9]+)\.(?<patch>[0-9]+)$'
          version: '4.5.6'

      - name: Print results
        run: echo ${{ steps.testparams.outputs.version }}

      - name: Verify results
        if: ${{ steps.testparams.outputs.version == '4.5.6' }}
        run: echo "Setting the version worked"
      - name: Verify results (negative case)
        if: ${{ steps.testparams.outputs.version != '4.5.6' }}
        run: |
          echo "Setting the version did not work"
          exit -1
