on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test functionality
        uses: ./ # Uses an action in the root directory
        id: test
        with:
          file: 'testproj/testproj.csproj'

      - name: Print results
        run: echo ${{ steps.test.outputs.version }}

      - name: Test functionality with params
        uses: ./ # Uses an action in the root directory
        id: testparams
        with:
          file: 'testproj/testproj.csproj'
          regex: '^(?<major>[0-9]+)\.(?<minor>[0-9]+)\.(?<patch>[0-9]+)$'
          xpath: '//PropertyGroup/Version'

      - name: Print results
        run: echo ${{ steps.testparams.outputs.version }}
